DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS temp CASCADE;


DROP TABLE IF EXISTS items;
CREATE TABLE items (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255),
    path VARCHAR(255),
    category VARCHAR(255)
);


DROP TABLE IF EXISTS temp CASCADE;
CREATE TABLE temp(
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    path VARCHAR(255) NOT NULL,
    category VARCHAR NOT NULL
 
);



